{"name": "Проверяем, что при передаче только логина приходит ошибка", "status": "skipped", "statusDetails": {"message": "XFAIL Баг API: падает с 504 ошибкой\n\nAssertionError: assert (504 == 400)\n +  where 504 = <Response [504]>.status_code", "trace": "self = <tests.TestCourierLogin object at 0x0000027B7025DF70>, payload = {'firstName': 'uudcmcybkb', 'login': 'hejmbpqzqm', 'password': 'ivpmjlppjn'}\n\n    @allure.title(\"Проверяем, что при передаче только логина приходит ошибка\")\n    @pytest.mark.xfail(reason=\"Баг API: падает с 504 ошибкой\")\n    def test_login_without_password_returns_error(self, payload):\n        response = requests.post(\"https://qa-scooter.praktikum-services.ru/api/v1/courier\", data=payload)\n        assert response.status_code == 201 and response.text == '{\"ok\":true}'\n        login = payload.get(\"login\")\n        response = requests.post(\"https://qa-scooter.praktikum-services.ru/api/v1/courier/login\",\n                                 data={\"login\": login})\n>       assert response.status_code == 400 and response.json()[\"message\"] == \"Недостаточно данных для входа\"\nE       assert (504 == 400)\nE        +  where 504 = <Response [504]>.status_code\n\ntests.py:67: AssertionError"}, "start": 1728238132455, "stop": 1728238192592, "uuid": "2eb3c5ad-3a0a-4200-ad52-bf18120377fb", "historyId": "5525694cd6ce5bd32c9a0aed16b01cce", "testCaseId": "5525694cd6ce5bd32c9a0aed16b01cce", "fullName": "tests.TestCourierLogin#test_login_without_password_returns_error", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(reason='Баг API: падает с 504 ошибкой')"}, {"name": "suite", "value": "tests"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-0KFG2SR"}, {"name": "thread", "value": "17772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests"}]}