{"name": "Проверяем, что без предварительного создания пользователя приходит ошибка, т.к. такого пользователя нет", "status": "passed", "start": 1728238192877, "stop": 1728238192974, "uuid": "b85a787a-9136-4e44-b0b9-b9188d27dfa2", "historyId": "6da87a93eb405355618df860d972ed05", "testCaseId": "6da87a93eb405355618df860d972ed05", "fullName": "tests.TestCourierLogin#test_login_nonexistent_user_returns_error", "labels": [{"name": "suite", "value": "tests"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-0KFG2SR"}, {"name": "thread", "value": "17772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests"}]}