{"name": "Проверяем, что при передаче только пароля приходит ошибка", "status": "passed", "start": 1728238192709, "stop": 1728238192871, "uuid": "0ee3602f-7b59-4127-9bb0-0a70c6137bec", "historyId": "db10a94adb5a175abfc2729c002decbe", "testCaseId": "db10a94adb5a175abfc2729c002decbe", "fullName": "tests.TestCourierLogin#test_login_without_login_returns_error", "labels": [{"name": "suite", "value": "tests"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-0KFG2SR"}, {"name": "thread", "value": "17772-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests"}]}